name: FArhan ali

on:
  push:
    branches: [ main ]

jobs:
  build-file:
    runs-on: ubuntu-latest

    concurrency:
        group: Deploy
        cancel-in-progress: true

    steps:
      - name: checkout
        uses: actions/checkout@v6.0.2
      - name: install node-js
        uses: actions/setup-node@v6.3.0
        with:
          node-version: 22.x

      - name: install dependencies
        run: npm install
      - name: build node-js
        run: npm run build
      - name: deploy app
        run: echo "deploying app...."
          
